config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  get 'articles/index'

  resources :articles do
    resources :comments
  end

  root to: 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to  :user
	has_many    :comments, dependent: :destroy
	validates :title, presence: {message: "Title cannot be blank!"}
	validates :body,  presence: {message: "Body cannot be blank!"}

	scope :sorted, lambda{order('title ASC')}


end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user

  validates :comment_body, presence: true

  def self.persisted
    where.not(id: nil)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :articles
  #has_many :comments
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_action :authenticate_user!, except: [:index,:show]

  def index
  
    @article=Article.all.sorted
   
  end

  def edit
    @article=Article.find(params[:id])
  end

  def update
  
    @article=Article.find(params[:id])
    if @article.update(article_params)
    flash[:success] = "Article has been updated"
    redirect_to article_path
    else
    flash.now[:danger]="Article has not been updated"
    render :edit
    end


  end

  def show
  
    @article=Article.find(params[:id])
    @comment= @article.comments.build
  end

  def new
    @article=Article.new

  end

  def create
    @article = current_user.articles.build(article_params)
    
   # @article = Article.new(article_params)
   # @article.user_id = current_user.id


    if @article.save
       flash[:success] = "Article has been created!"
       redirect_to articles_path
    else
       #flash[:danger]="Article has not been created"
       #redirect_to articles_path
       render :new
    end

  end

  def destroy

    
    @article = Article.find(params[:id])


    #raise current_user.id.inspect
    #raise @article.user.id.inspect

  if (@article.user.id==current_user.id)

    if @article.destroy
      flash[:success] = "Article has been deleted"
      redirect_to articles_path
    end
  else
      flash[:danger] = "Article has not deleted"
      redirect_to root_path

  end



   end


  private

    def article_params
      params.require(:article).permit(:title,:body)
    end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@article=Article.find(params[:article_id])
		@comment= @article.comments.build(comment_params)
		@comment.user= current_user
		if @comment.save
			flash[:success]= "Comment has been created"
			else
			flash.now[:danger]="Comment not saved"
		end

        redirect_to article_path(@article)

	end 

	private

	def comment_params

        params.require(:comment).permit(:comment_body)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper



end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/edit.html.erb
<h3 class='text-center'> Edit New Article</h3>
<div class='row'>
<div class='col-md-12'>
<%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>

<% if @article.errors.any? %>

<%= pluralize(@article.errors.count,"error") %>

<% @article.errors.each do |attr,msg| %>

<%=msg %>

<%end%>


<% end %>


<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :title %>
</div>
<div class='col-md-11'>
<%= f.text_field :title, class: 'form-control', placeholder: 'Title of article', autofocus: true %>
</div>
</div>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :body %>
</div>
<div class='col-md-11'>
<%= f.text_area :body, rows: 10, class: 'form-control', placeholder: 'Body of article' %>
</div>
</div>
<div class='form-group'>
<div class='col-md-offset-1 col-md-11'>
<%= f.submit class: 'btn btn-primary btn-lg pull-right' %>
</div>
</div>
<% end %>
</div>
</div>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<% if current_user %>
<%= link_to "New Article", new_article_path %>
<% end %>

<br/>

<% @article.each do |article| %>

  <b><%= link_to article.title, article_path(article)%> </b>
  <small>Created by <%=article.user.email %>
  </small>
  <br/>
  <%=article.body%>
  </br>

  </small>

<%end%>

app/views/articles/new.html.erb
<h3 class='text-center'> Adding New Article</h3>
<div class='row'>
<div class='col-md-12'>
<%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>

<% if @article.errors.any? %>

<%= pluralize(@article.errors.count,"error") %>

<% @article.errors.each do |attr,msg| %>

<%=msg %>

<%end%>


<% end %>


<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :title %>
</div>
<div class='col-md-11'>
<%= f.text_field :title, class: 'form-control', placeholder: 'Title of article', autofocus: true %>
</div>
</div>
<div class='form-group'>
<div class='control-label col-md-1'>
<%= f.label :body %>
</div>
<div class='col-md-11'>
<%= f.text_area :body, rows: 10, class: 'form-control', placeholder: 'Body of article' %>
</div>
</div>
<div class='form-group'>
<div class='col-md-offset-1 col-md-11'>
<%= f.submit class: 'btn btn-primary btn-lg pull-right' %>
</div>
</div>
<% end %>
</div>
</div>

app/views/articles/show.html.erb
<br/>

<%= @article.title %>
[<%=@article.created_at.strftime("%b %d, %y")%>]
<%= @article.body %>

<% if (current_user && (current_user.id == @article.user.id)) %>

<%= link_to "Edit Article", edit_article_path(@article) %>
<br/>
<%= link_to "Delete Article", article_path(@article), method: :delete, data: {confirm: "Are you sure?"} %>

<%end%>

<br/>

<div class='col-md-12'>
<%= form_for [@article, @comment ], :html => {class: "form-horizontal", role: "form"} do |f| %>
<% if @comment.errors.any? %>
<div class="panel panel-danger col-md-offset-1">
<div class="panel-heading">
<h2 class="panel-title">
<%= pluralize(@comment.errors.count, "error") %>
prohibited this article from being saved:
</h2>
<div class="panel-body">
<ul>
<% @comment.errors.full_messages.each do |msg| %>
<li>
<%= msg %>
</li>
<% end %>
</ul>
</div>
</div>
</div>
<% end %>
<div class='form-group'>
<div class='control-label col-md-2'>
<%= f.label :comment_body, 'New Comment' %>
</div>
<div class='col-md-10'>
<%= f.text_area :comment_body, rows: 10, class: 'form-control', placeholder: 'Your comment' %>
</div>
</div>
<div class='form-group'>
<div class='col-md-offset-2 col-md-10'>
<%= f.submit "Add Comment", class: 'btn btn-primary btn-lg pull-right' %>
</div>
</div>
<% end %>
</div>
<div class='col-md-12'>
<header>
<h2>Comments</h2>
</header>
<div class="col-md-10">

<% if @article.comments.any? %>
<% @article.comments.persisted.each do |comment| %>
<div class="comment-body">
<%= comment.comment_body %>
</div>
<div class="comment-time">

</div>
<hr>
<% end %>
<% else %>
There are no comments to show.
<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to "Blog App", root_path %>

</br>

<% if user_signed_in? %>
Signed in as <%= "#{current_user.email}" %>
<br/>
<%=link_to "SignOut", destroy_user_session_path, method: :delete %>
<br/>
<% end %>
<%= link_to "Register", new_user_registration_path %>

<%= link_to "Sign in", new_user_session_path %>


<% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href='#' class='close' data-dismiss='alert'>&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
      <% end %>
      

<%= yield %>

</body>
</html>